
server:
  port: 8889

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080/auth}
  realm: ${KEYCLOAK_REALM:wasabih}
  resource: backend
  public-client: false
  principal-attribute: preferred_id